//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWeb.UI.WebformMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chavewhatsapp
    {
        public string TelefoneOrcozol { get; set; }
        public string ChaveWhatsApp1 { get; set; }
        public string MaquinaVirtual { get; set; }
        public string IpMaquinaVirtual { get; set; }
        public string Carteira { get; set; }
        public Nullable<short> StatusRoboEnvio { get; set; }
        public Nullable<short> StatusRoboLeitura { get; set; }
        public Nullable<System.DateTime> DataHoraStatusEnvio { get; set; }
        public Nullable<System.DateTime> DataHoraStatusLeitura { get; set; }
    }
}
