//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWeb.UI.WebformMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Mensagem = new HashSet<Mensagem>();
            this.Telefones = new HashSet<Telefones>();
        }
    
        public string TelefoneCliente { get; set; }
        public string Situacao { get; set; }
        public byte[] UrlImagem { get; set; }
        public Nullable<System.DateTime> DataHoraRegistro { get; set; }
        public string NomeCliente { get; set; }
        public Nullable<System.DateTime> DataVisualizacao { get; set; }
        public string Cpf { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Pendente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensagem> Mensagem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefones> Telefones { get; set; }
        public virtual Situacao Situacao1 { get; set; }
    }
}
