//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWeb.UI.WebformMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensagem
    {
        public int Id { get; set; }
        public string TelefoneCliente { get; set; }
        public Nullable<System.DateTime> DataMensagem { get; set; }
        public Nullable<System.DateTime> DataInclusao { get; set; }
        public Nullable<short> Tipo { get; set; }
        public string Mensagem1 { get; set; }
        public Nullable<bool> Enviada { get; set; }
        public string Sequencial { get; set; }
        public Nullable<int> Usuario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
