//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWeb.UI.WebformMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WWebEntities : DbContext
    {
        public WWebEntities()
            : base("name=WWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mensagem> Mensagem { get; set; }
        public virtual DbSet<MensagemPredefinida> MensagemPredefinida { get; set; }
        public virtual DbSet<Telefones> Telefones { get; set; }
        public virtual DbSet<Configuracao> Configuracao { get; set; }
        public virtual DbSet<Acesso> Acesso { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Chavewhatsapp> Chavewhatsapp { get; set; }
        public virtual DbSet<Situacao> Situacao { get; set; }
        public virtual DbSet<Agenda> Agenda { get; set; }
    
        public virtual int SPIGravarMensagem(string telefoneCliente, Nullable<System.DateTime> dataMensagem, Nullable<System.DateTime> dataInclusao, Nullable<short> tipo, string mensagem, Nullable<bool> enviada, string sequencial)
        {
            var telefoneClienteParameter = telefoneCliente != null ?
                new ObjectParameter("TelefoneCliente", telefoneCliente) :
                new ObjectParameter("TelefoneCliente", typeof(string));
    
            var dataMensagemParameter = dataMensagem.HasValue ?
                new ObjectParameter("DataMensagem", dataMensagem) :
                new ObjectParameter("DataMensagem", typeof(System.DateTime));
    
            var dataInclusaoParameter = dataInclusao.HasValue ?
                new ObjectParameter("DataInclusao", dataInclusao) :
                new ObjectParameter("DataInclusao", typeof(System.DateTime));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(short));
    
            var mensagemParameter = mensagem != null ?
                new ObjectParameter("Mensagem", mensagem) :
                new ObjectParameter("Mensagem", typeof(string));
    
            var enviadaParameter = enviada.HasValue ?
                new ObjectParameter("Enviada", enviada) :
                new ObjectParameter("Enviada", typeof(bool));
    
            var sequencialParameter = sequencial != null ?
                new ObjectParameter("Sequencial", sequencial) :
                new ObjectParameter("Sequencial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPIGravarMensagem", telefoneClienteParameter, dataMensagemParameter, dataInclusaoParameter, tipoParameter, mensagemParameter, enviadaParameter, sequencialParameter);
        }
    
        public virtual ObjectResult<SPSCliente_Result> SPSCliente(Nullable<int> parametro)
        {
            var parametroParameter = parametro.HasValue ?
                new ObjectParameter("Parametro", parametro) :
                new ObjectParameter("Parametro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSCliente_Result>("SPSCliente", parametroParameter);
        }
    
        public virtual ObjectResult<SPSClienteOnline_Result> SPSClienteOnline(Nullable<int> qtd)
        {
            var qtdParameter = qtd.HasValue ?
                new ObjectParameter("Qtd", qtd) :
                new ObjectParameter("Qtd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSClienteOnline_Result>("SPSClienteOnline", qtdParameter);
        }
    
        public virtual ObjectResult<SPSClientePeloNumeroOrcozol_Result> SPSClientePeloNumeroOrcozol(string telefoneOrcozol)
        {
            var telefoneOrcozolParameter = telefoneOrcozol != null ?
                new ObjectParameter("TelefoneOrcozol", telefoneOrcozol) :
                new ObjectParameter("TelefoneOrcozol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSClientePeloNumeroOrcozol_Result>("SPSClientePeloNumeroOrcozol", telefoneOrcozolParameter);
        }
    
        public virtual ObjectResult<SPSClientePeloTelefone_Result> SPSClientePeloTelefone(string telefoneCliente)
        {
            var telefoneClienteParameter = telefoneCliente != null ?
                new ObjectParameter("TelefoneCliente", telefoneCliente) :
                new ObjectParameter("TelefoneCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSClientePeloTelefone_Result>("SPSClientePeloTelefone", telefoneClienteParameter);
        }
    
        public virtual ObjectResult<SPSEnviarMensagemNumeroOrcozol_Result> SPSEnviarMensagemNumeroOrcozol(string telefoneOrcozol)
        {
            var telefoneOrcozolParameter = telefoneOrcozol != null ?
                new ObjectParameter("TelefoneOrcozol", telefoneOrcozol) :
                new ObjectParameter("TelefoneOrcozol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSEnviarMensagemNumeroOrcozol_Result>("SPSEnviarMensagemNumeroOrcozol", telefoneOrcozolParameter);
        }
    
        public virtual ObjectResult<SPSMensagemPeloCliente_Result> SPSMensagemPeloCliente(string telefoneCliente)
        {
            var telefoneClienteParameter = telefoneCliente != null ?
                new ObjectParameter("TelefoneCliente", telefoneCliente) :
                new ObjectParameter("TelefoneCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSMensagemPeloCliente_Result>("SPSMensagemPeloCliente", telefoneClienteParameter);
        }
    
        public virtual ObjectResult<SPSTelefonePeloCliente_Result> SPSTelefonePeloCliente(string telefoneCliente)
        {
            var telefoneClienteParameter = telefoneCliente != null ?
                new ObjectParameter("TelefoneCliente", telefoneCliente) :
                new ObjectParameter("TelefoneCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSTelefonePeloCliente_Result>("SPSTelefonePeloCliente", telefoneClienteParameter);
        }
    
        public virtual ObjectResult<SPSTelefonePeloNumeroOrcozol_Result> SPSTelefonePeloNumeroOrcozol(string telefoneOrcozol)
        {
            var telefoneOrcozolParameter = telefoneOrcozol != null ?
                new ObjectParameter("TelefoneOrcozol", telefoneOrcozol) :
                new ObjectParameter("TelefoneOrcozol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSTelefonePeloNumeroOrcozol_Result>("SPSTelefonePeloNumeroOrcozol", telefoneOrcozolParameter);
        }
    
        public virtual int SPUClienteVisualizacao(string telefoneCliente)
        {
            var telefoneClienteParameter = telefoneCliente != null ?
                new ObjectParameter("TelefoneCliente", telefoneCliente) :
                new ObjectParameter("TelefoneCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPUClienteVisualizacao", telefoneClienteParameter);
        }
    
        public virtual int SPUMensagemEnviada(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPUMensagemEnviada", idParameter);
        }
    
        public virtual ObjectResult<SPUMensagensVisualizadas_Result> SPUMensagensVisualizadas(string telefoneCliente)
        {
            var telefoneClienteParameter = telefoneCliente != null ?
                new ObjectParameter("TelefoneCliente", telefoneCliente) :
                new ObjectParameter("TelefoneCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPUMensagensVisualizadas_Result>("SPUMensagensVisualizadas", telefoneClienteParameter);
        }
    
        public virtual ObjectResult<SPSClienteComStatus_Result> SPSClienteComStatus(Nullable<int> parametro)
        {
            var parametroParameter = parametro.HasValue ?
                new ObjectParameter("Parametro", parametro) :
                new ObjectParameter("Parametro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSClienteComStatus_Result>("SPSClienteComStatus", parametroParameter);
        }
    
        public virtual ObjectResult<SPSClienteOnLinePeloUsuario_Result> SPSClienteOnLinePeloUsuario(Nullable<int> usuario, string telefoneCliente)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(int));
    
            var telefoneClienteParameter = telefoneCliente != null ?
                new ObjectParameter("TelefoneCliente", telefoneCliente) :
                new ObjectParameter("TelefoneCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSClienteOnLinePeloUsuario_Result>("SPSClienteOnLinePeloUsuario", usuarioParameter, telefoneClienteParameter);
        }
    
        public virtual ObjectResult<SPSClientePorData_Result> SPSClientePorData(Nullable<System.DateTime> inicio, Nullable<System.DateTime> fim)
        {
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(System.DateTime));
    
            var fimParameter = fim.HasValue ?
                new ObjectParameter("Fim", fim) :
                new ObjectParameter("Fim", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSClientePorData_Result>("SPSClientePorData", inicioParameter, fimParameter);
        }
    
        public virtual ObjectResult<SPSMensagemPeriodo_Result> SPSMensagemPeriodo(Nullable<System.DateTime> inicio, Nullable<System.DateTime> fim)
        {
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(System.DateTime));
    
            var fimParameter = fim.HasValue ?
                new ObjectParameter("Fim", fim) :
                new ObjectParameter("Fim", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSMensagemPeriodo_Result>("SPSMensagemPeriodo", inicioParameter, fimParameter);
        }
    
        public virtual ObjectResult<SPSMensagemUsuarioPeriodo_Result> SPSMensagemUsuarioPeriodo(Nullable<System.DateTime> inicio, Nullable<System.DateTime> fim)
        {
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(System.DateTime));
    
            var fimParameter = fim.HasValue ?
                new ObjectParameter("Fim", fim) :
                new ObjectParameter("Fim", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPSMensagemUsuarioPeriodo_Result>("SPSMensagemUsuarioPeriodo", inicioParameter, fimParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SPSQtdClienteTelefone(string telefoneOrcozol)
        {
            var telefoneOrcozolParameter = telefoneOrcozol != null ?
                new ObjectParameter("TelefoneOrcozol", telefoneOrcozol) :
                new ObjectParameter("TelefoneOrcozol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SPSQtdClienteTelefone", telefoneOrcozolParameter);
        }
    }
}
